[pytest]
testpaths = ecommerce-autotest/testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: smoke tests
    login: login module tests
    product: product module tests
    order: order module tests
    user: user module tests
    permission: permission module tests

